apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "filebrowser.fullname" . }}
  labels:
    {{- include "filebrowser.labels" . | nindent 4 }}
data:
  filebrowser.json: |
    {
      "port": {{ .Values.service.inport }},
      "baseURL": "",
      "address": "0.0.0.0",
      "log": "stdout",
      "database": "/app/data/database.db",
      "root": "/app/data/srv"
    }
